Repository snowplow/dbt-snowplow-normalize, pull requests merged in 2022-12, with the labels that each got.

#11 Release/snowplow normalize/0.1.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/labels.yml
  .github/pull_request_template.md
  .github/workflows/no-response.yml
  .github/workflows/release.yml
  .github/workflows/triage-labeler.yml
  .github/workflows/unit_test.yml
  .gitignore
  CHANGELOG
  README.md
  dbt_project.yml
  docs/.nojekyll
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/markdown/snowplow_normalize_base_docs.md
  docs/markdown/snowplow_normalize_common_cols.md
  docs/markdown/snowplow_normalize_overview.md
  docs/run_results.json
  macros/allow_refresh.sql
  macros/normalize_events.sql
  macros/schema.yml
  macros/snakeify_case.sql
  macros/users_table.sql
  models/.gitkeep
  models/base/manifest/base_manifest.yml
  models/base/manifest/snowplow_normalize_incremental_manifest.sql
  models/base/scratch/base_scratch.yml
  models/base/scratch/bigquery/snowplow_normalize_base_events_this_run.sql
  models/base/scratch/databricks/snowplow_normalize_base_events_this_run.sql
  models/base/scratch/snowflake/snowplow_normalize_base_events_this_run.sql
  models/base/scratch/snowplow_normalize_base_new_event_limits.sql
  models/base/src_base.yml
  packages.yml
  selectors.yml
  utils/__init__.py
  utils/example_event_split_config.json
  utils/example_normalize_config.json
  utils/functions/snowplow_model_gen_funcs.py
  utils/requirements.txt
  utils/snowplow_normalize_model_gen.py
  utils/snowplow_split_events_model_gen.py
  utils/tests/__init__.py
  utils/tests/expected/custom_table_name2_1.sql
  utils/tests/expected/custom_table_name3_2.sql
  utils/tests/expected/custom_table_name4_1.sql
  utils/tests/expected/event_name1_1.sql
  utils/tests/expected/test_events_users.sql
  utils/tests/expected/test_normalized_events.sql
  utils/tests/test_model_gen.py
  utils/tests/test_normalize_config.json
  utils/tests/test_normalize_config_duplicate.json
Labels: cla:yes

#18 Drop support for dbt versions below 1.3 (Close #17)
  dbt_project.yml
  models/base/manifest/snowplow_normalize_incremental_manifest.sql
  packages.yml
Labels: category:breaking_change

#14 Add unit tests for macros
  .github/workflows/integration_tests.yml
  integration_tests/.gitignore
  integration_tests/.scripts/integration_test.sh
  integration_tests/README.md
  integration_tests/ci/profiles.yml
  integration_tests/dbt_project.yml
  integration_tests/macros/test_normalize_events.sql
  integration_tests/macros/test_snakeify_case.sql
  integration_tests/macros/test_users_table.sql
  integration_tests/packages.yml
  macros/normalize_events.sql
  macros/schema.yml
  macros/users_table.sql
Labels: category:tests
